# Specify foam-extend-4.0 docker image as the build environment
image: philippic/foam-extend-4.0-ubuntu18.04.gfortran:latest

# Increase memory as gcc seems to run out of memory and give an internal error
options:
  size: 2x

pipelines:
  default:
    - step:
        script:
          # Compile repository
          - ./Allwmake